### PR TITLE
Display multiple images implementation, some minor fixes

### LINKED ISSUE #301: Displaying multiple images
Should displaying multiple images happen in multiple windows or in one window?

### PR DESCRIPTION
**Pull request by lazypassion**
#301

### CODE REVIEW

**Comment by theotherphil** [comment]
Thanks! I’ll have a look through this tomorrow.

**Comment by lazypassion** [comment]
I was getting segmentation fault's sometimes when running it on ubuntu 18.04, so tell me if you experience any issues. It seems to be a problem with sdl2 because it works fine on windows.

**Comment by lazypassion** [comment]
Yeah it looks like it can, I'll make the change if nothing weird crops up

File: src/window.rs [hunk 1]
```diff
@@ -23,53 +47,93 @@ pub fn display_image(title: &str, image: &RgbaImage, window_width: u32, window_h
...
+    let mut windows: Vec<sdl2::video::Window> = Vec::with_capacity(images.len());
+    let mut window_visibility: Vec<bool> = Vec::with_capacity(images.len());
+    for _ in 0..images.len() {
+        let mut window = video_subsystem
+            .window(title, window_width, window_height)
+            .position_centered()
+            .resizable()
+            .build()
+            .expect("couldn't create window");
+
```
Comment (theotherphil) [inline src/window.rs]: Creating all of the images in the same location is a bit confusing. You could use `set_position` to stagger each window by some multiple of its index.

Comment (lazypassion) [reply src/window.rs]: I have them staggered, however there is an issue if there are too many windows it is possible that they are rendered off screen. So i'll have to add some code to prevent that. And by too many windows, I mean around 20 and more.

**Comment by lazypassion** [comment]
If and when you merge, can you squash and merge please?

**Comment by lazypassion** [comment]
@theotherphil is this how u ping?

**Comment by theotherphil** [comment]
Thanks!
